using CSharpFunctionalExtensions;
using DinnerSpinner.Domain.Abstractions;
using DinnerSpinner.Domain.Shared;

namespace DinnerSpinner.Domain.Features.Categories;

public sealed record CategoryId : IValueObject
{
    public static readonly string InvalidMessage = $"{nameof(CategoryId)} must be a positive integer.";
    public static readonly string RequiredMessage = $"{nameof(CategoryId)} is required";

    public int Value { get; }
    private CategoryId(int value) => Value = value;

    public static Result<CategoryId, Error> Create
        (int value) => value <= 0 || value == default
            ? (Result<CategoryId, Error>)Error.Validation("Category.Error.Invalid", InvalidMessage)
            : (Result<CategoryId, Error>)new CategoryId(value);

    // Equality members are automatically generated by the record type, so no need to override them like we used to in
    // the class type ValueObject.

    // The ToString method is also automatically generated, but override it to provide a more meaningful
    // representation, CategoryId in this case. Useful for debugging and logging purposes, as it allows us to easily see
    // the value of the CategoryId (instead of the default record representation) when it is printed or logged.
    public override string ToString() => Value.ToString();

    // Entity Framework requires a parameterless constructor for entity materialization
    private CategoryId() { }
}