using CSharpFunctionalExtensions;

namespace DinnerSpinner.Domain.Features.Categories;

public sealed record CategoryId
{
    private const string DisplayName = nameof(CategoryId);
    internal const string InvalidMessage = $"{DisplayName} must be a positive integer.";

    public int Value { get; }

    private CategoryId(int value)
        => Value = value;

    public static Result<CategoryId> Create(int value)
    {
        if (value <= 0)
        {
            return Result.Failure<CategoryId>(InvalidMessage);
        }

        return Result.Success(new CategoryId(value));
    }

    // Equality members are automatically generated by the record type, so no need to override them like we used to in
    // the class type.

    // The ToString method is also automatically generated, but override it to provide a more meaningful
    // representation, CategoryId in this case. Useful for debugging and logging purposes, as it allows us to easily see
    // the value of the CategoryId (instead of the default record representation) when it is printed or logged.
    public override string ToString() => Value.ToString();

    // Entity Framework requires a parameterless constructor for entity materialization
    private CategoryId() { }
}